id: P008027
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016999
  title: གྲུབ་ཆེན་ཏཻ་ལོ་པ་ཤེས་རབ་བཟང་པོའི་རྣམ་ཐར
  author: ''
  volumes:
    8ecfb873722f4dd7bfe186381a703426:
      image_group_id: I00EGS1017003
      title: ''
      volume_number: 1
      total_pages: 118
ebook_metadata:
  title: གྲུབ་ཆེན་ཏཻ་ལོ་པ་ཤེས་རབ་བཟང་པོའི་རྣམ་ཐར
  author: ''
  sku: P008027
  cover: cover.jpg
  layers:
  - pagination
