id: P008027
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:56:27.751765
source_metadata:
  id: bdr:W00EGS1016999
  title: གྲུབ་ཆེན་ཏཻ་ལོ་པ་ཤེས་རབ་བཟང་པོའི་རྣམ་ཐར
  author: ''
  volumes:
    f2804f878f7b4611b5fcdc85d77cc8f5:
      image_group_id: I00EGS1017003
      title: Volume 1 of grub chen tai lo pa shes rab bzang po'i rnam thar
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
