id: IFD14B1FC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T01:03:29+00:00'
last_modified: '2022-06-08T17:54:52.522826+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016999
  title: གྲུབ་ཆེན་ཏཻ་ལོ་པ་ཤེས་རབ་བཟང་པོའི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E287:
      image_group_id: I00EGS1017003
      title: Volume 1 of grub chen tai lo pa shes rab bzang po'i rnam thar
      total_pages: 118
      order: 1
      base_file: E287.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
